name: surround_frequency_generator
description: A package to create surround sound effects with a frequency generator using Web Audio API
version: 1.0.0
repository: https://github.com/Cyberneom/surround_frequency_generator

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  webview_flutter_wkwebview: ^3.7.1
  webview_flutter_platform_interface: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
